export const Prizes = [
  "A Plastic lobster",
  "A dog biscuit",
  "A Nit comb",
  "some false eyelashes",
  "Spider catcher",
  "Ear cleaning kit",
  "String of garlic",
  "Can of Polo mint holes",
  "Eight-course insect meal",
  "Heart shaped bed",
  "One teabag",
  "Grow your own sprout kit",
  "Remote control for curtains",
  "Personalised baked bean",
  "Pair of green lucky pants",
  "a premium graded stallion",
  "Jar of fake snow",
  "Your portrait drawn on a nut",
  "Six months supply of diapers",
  "Feature as a character in a novel",
  "Dragon's blood",
  "Peanut tree",
  "100 Chinese dinner sets",
  "Spork",
  "Empty tin to keep negative thoughts in",
  "Book of knitting patterns for dog clothes",
  "Car tyre",
  "Chocolate teapot",
  "Chicken manure",
  "'Octonauts' DVD",
  "Empty apple barrel",
  "Year's supply of salad cream",
  "Vampire teeth",
  "Life size Doraemon cutout",
  "Nose cleaner",
  "Bowling ball",
  "Inflatable flea",
  "Life sized baby dolphin toy",
  "Disposable underwear",
  "Live turkey",
  "Booger picking device",
  "face cleanser",
  "Inflatable worm",
  "Camel ride (at the local shopping centre)",
  "Photo of someone eating a yoghurt",
];
