export const Prizes = [
  "a plastic lobster",
  "a dog biscuit",
  "a toothless comb",
  "some false eyelashes",
  "a spider catcher",
  "an ear cleaning kit",
  "a string of garlic",
  "a can of Polo mint holes",
  "an eight-course vegan meal",
  "a heart shaped bed",
  "one teabag",
  "a grow-your-own-sprout kit",
  "a remote control for curtains",
  "a personalised baked bean",
  "a pair of green lucky pants",
  "a premium graded goat",
  "a jar of fake snow",
  "a self-portrait drawn on a nut",
  "six months supply of diapers",
  "a bristleless toothbrush",
  "a solar-powered torchlight",
  "a coconut tree",
  "100 chicken rice sets",
  "a spork",
  "an empty tin to keep negative thoughts in",
  "a book of knitting patterns for dog clothes",
  "a punctured car tyre",
  "a chocolate teapot",
  "a box of non-matching shoelaces ",
  "an 'Octonauts' DVD",
  "an empty apple barrel",
  "a year's supply of salad cream",
  "a set of fake teeth",
  "a life size Doraemon cutout",
  "a nose cleaner",
  "a bowling ball",
  "an inflatable moose",
  "a life sized baby dolphin toy",
  "a new pair of disposable underwear",
  "a talking turkey",
  "a booger picking device",
  "a face cleanser",
  "a cute cuddly worm",
  "a camel ride (at the local shopping centre)",
  "a photo of yourself eating a yoghurt",
];
